apiVersion: v2
name: valid8or-plugin-vsphere
description: Perform various vsphere validations (Role Privileges, Region/Zone Tags)
type: application
version: 0.0.2 # x-release-please-version
appVersion: "0.0.2" # x-release-please-version
