---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - vspherevalidators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - vspherevalidators/finalizers
  verbs:
  - update
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - vspherevalidators/status
  verbs:
  - get
  - patch
  - update
