apiVersion: validation.spectrocloud.labs/v1alpha1
kind: VsphereValidator
metadata:
  labels:
    app.kubernetes.io/name: vspherevalidator
    app.kubernetes.io/instance: vspherevalidator-sample
    app.kubernetes.io/part-of: validator-plugin-vsphere
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: validator-plugin-vsphere
  name: vspherevalidator-explicit-auth
  namespace: validator
spec:
  auth:
    account:
      insecure: true
      username: "user@vsphere.local"
      password: "password"
      host: "vcenter.example.com"
  datacenter: "Datacenter"
  tagValidationRules:
    - name: "Folder tag validation"
      clusterName: "Cluster2"
      entityType: "folder"
      entityName: "sp-prakash"
      tag: "owner"