apiVersion: validation.spectrocloud.labs/v1alpha1
kind: VsphereValidator
metadata:
  labels:
    app.kubernetes.io/name: vspherevalidator
    app.kubernetes.io/instance: vspherevalidator-sample
    app.kubernetes.io/part-of: validator-plugin-vsphere
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: validator-plugin-vsphere
  name: vspherevalidator-entity-privilege
  namespace: validator
spec:
  auth:
    secretName: vsphere-creds
  datacenter: "Datacenter"
  privilegeValidationRules:
    - name: "Deploy VM to vapp test-vapp"
      entityName: "sp-prakash"
      entityType: "Folder"
      privileges:
      - "VirtualMachine.Config.AddExistingDisk"
      - "VirtualMachine.Config.AddNewDisk"
      propagation:
        enabled: true
        groupPrincipals:
        - VSPHERE.LOCAL\my-group
        propagated: true