apiVersion: validation.spectrocloud.labs/v1alpha1
kind: VsphereValidator
metadata:
  labels:
    app.kubernetes.io/name: vspherevalidator
    app.kubernetes.io/instance: vspherevalidator-sample
    app.kubernetes.io/part-of: valid8or-plugin-vsphere
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: valid8or-plugin-vsphere
  name: vspherevalidator
  namespace: valid8or
spec:
  datacenter: "Datacenter"
  computeResourceRules:
    - name: "rp-cluster2-palette-advanced-projects check resources"
      clusterName: Cluster2
      scope: resourcepool
      entityName: "rp-cluster2-palette-advanced-projects"
      nodepoolResourceRequirements:
        - name: master-pool
          numberOfNodes: 3
          cpu: "9GHz"
          memory: 16Gi
          diskSpace: 80Gi
        - name: worker-pool
          numberOfNodes: 2
          cpu: "10GHz"
          memory: 32Gi
          diskSpace: 100Gi
  auth:
    secretName: validator-secret
  entityPrivilegeValidationRules:
    - name: "Deploy VM to vapp test-vapp"
      clusterName: "Cluster2"
      entityName: "test-vapp"
      entityType: "vapp"
      privileges:
      - "VirtualMachine.Config.AddExistingDisk"
      - "VirtualMachine.Config.AddNewDisk"
      - "VirtualMachine.Config.AdvancedConfig"
      - "VirtualMachine.Config.Annotation"
      - "VirtualMachine.Config.CPUCount"
      - "VirtualMachine.Config.ChangeTracking"
      - "VirtualMachine.Config.DiskExtend"
      - "VirtualMachine.Config.DiskLease"
      - "VirtualMachine.Config.EditDevice"
      - "VirtualMachine.Config.HostUSBDevice"
      - "VirtualMachine.Config.ManagedBy"
      - "VirtualMachine.Config.Memory"
      - "VirtualMachine.Config.MksControl"
      - "VirtualMachine.Config.QueryFTCompatibility"
      - "VirtualMachine.Config.QueryUnownedFiles"
      - "VirtualMachine.Config.RawDevice"
      - "VirtualMachine.Config.ReloadFromPath"
      - "VirtualMachine.Config.RemoveDisk"
      - "VirtualMachine.Config.Rename"
      - "VirtualMachine.Config.ResetGuestInfo"
      - "VirtualMachine.Config.Resource"
      - "VirtualMachine.Config.Settings"
      - "VirtualMachine.Config.SwapPlacement"
      - "VirtualMachine.Config.ToggleForkParent"
      - "VirtualMachine.Config.UpgradeVirtualHardware"
      - "VirtualMachine.GuestOperations.Execute"
      - "VirtualMachine.GuestOperations.Modify"
      - "VirtualMachine.GuestOperations.ModifyAliases"
      - "VirtualMachine.GuestOperations.Query"
      - "VirtualMachine.GuestOperations.QueryAliases"
      - "VirtualMachine.Hbr.ConfigureReplication"
      - "VirtualMachine.Hbr.MonitorReplication"
      - "VirtualMachine.Hbr.ReplicaManagement"
      - "VirtualMachine.Interact.Backup"
      - "VirtualMachine.Interact.ConsoleInteract"
      - "VirtualMachine.Interact.DeviceConnection"
      - "VirtualMachine.Interact.PowerOff"
      - "VirtualMachine.Interact.PowerOn"
      - "VirtualMachine.Interact.PutUsbScanCodes"
      - "VirtualMachine.Interact.SetCDMedia"
      - "VirtualMachine.Interact.SetFloppyMedia"
      - "VirtualMachine.Inventory.Create"
      - "VirtualMachine.Inventory.CreateFromExisting"
      - "VirtualMachine.Inventory.Delete"
      - "VirtualMachine.Inventory.Move"
      - "VirtualMachine.Inventory.Register"
      - "VirtualMachine.Inventory.Unregister"
      - "VirtualMachine.Namespace.Event"
      - "VirtualMachine.Namespace.EventNotify"
      - "VirtualMachine.Namespace.Management"
      - "VirtualMachine.Namespace.ModifyContent"
      - "VirtualMachine.Namespace.Query"
      - "VirtualMachine.Namespace.ReadContent"
      - "VirtualMachine.Provisioning.Clone"
      - "VirtualMachine.Provisioning.CloneTemplate"
      - "VirtualMachine.Provisioning.CreateTemplateFromVM"
      - "VirtualMachine.Provisioning.Customize"
      - "VirtualMachine.Provisioning.DeployTemplate"
      - "VirtualMachine.Provisioning.DiskRandomAccess"
      - "VirtualMachine.Provisioning.DiskRandomRead"
      - "VirtualMachine.Provisioning.FileRandomAccess"
      - "VirtualMachine.Provisioning.GetVmFiles"
      - "VirtualMachine.Provisioning.MarkAsTemplate"
      - "VirtualMachine.Provisioning.MarkAsVM"
      - "VirtualMachine.Provisioning.ModifyCustSpecs"
      - "VirtualMachine.Provisioning.PromoteDisks"
      - "VirtualMachine.Provisioning.PutVmFiles"
      - "VirtualMachine.Provisioning.ReadCustSpecs"
      - "VirtualMachine.State.CreateSnapshot"
      - "VirtualMachine.State.RemoveSnapshot"
      - "VirtualMachine.State.RenameSnapshot"
      - "VirtualMachine.State.RevertToSnapshot"
  tagValidationRules:
    - name: "Datacenter k8s-region tag validation"
      entityType: "vm"
      entityName: "ubuntu-test-mig-multi-disk"
      tag: "owner"
    - name: "Folder tag validation"
      clusterName: "Cluster2"
      entityType: "folder"
      entityName: "sp-prakash"
      tag: "owner"
  rolePrivilegeValidationRules:
    - name: tmpadmin@vsphere.local
      privileges:
        - Cns.Searchable
        - Datastore.Browse
        - InventoryService.Tagging.CreateTag
        - InventoryService.Tagging.EditTag
        - Network.Assign
        - Sessions.ValidateSession
        - StorageProfile.View
        - StorageViews.View