apiVersion: validation.spectrocloud.labs/v1alpha1
kind: VsphereValidator
metadata:
  labels:
    app.kubernetes.io/name: vspherevalidator
    app.kubernetes.io/instance: vspherevalidator-sample
    app.kubernetes.io/part-of: valid8or-plugin-vsphere
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: valid8or-plugin-vsphere
  name: vspherevalidator
  namespace: valid8or
spec:
  auth:
    secretName: validator-secret
  regionZoneValidationRule:
    regionCategoryName: "k8s-region"
    zoneCategoryName: "k8s-zone"
    datacenter: "Datacenter"
    clusters:
      - Cluster1
      - Cluster2
  rules:
    - name: Cns.Searchable
      description: Validates that the root-level role has the Cns.Searchable privilege
      isEnabled: true
      severity: error
      ruleType: VMwareRolePrivilege
      expressions:
        - '"Cns.Searchable" IN (vmware_user_privileges)'
    - name: Datastore.Browse
      description: Validates that the root-level role has the Datastore.Browse privilege
      isEnabled: true
      severity: error
      ruleType: VMwareRolePrivilege
      expressions:
        - '"Datastore.Browse" IN (vmware_user_privileges)'
    - name: InventoryService.Tagging.CreateTag
      description: >-
        Validates that the root-level role has the
        InventoryService.Tagging.CreateTag privilege
      isEnabled: true
      severity: error
      ruleType: VMwareRolePrivilege
      expressions:
        - '"InventoryService.Tagging.CreateTag" IN (vmware_user_privileges)'
    - name: InventoryService.Tagging.EditTag
      description: >-
        Validates that the root-level role has the InventoryService.Tagging.EditTag
        privilege
      isEnabled: true
      severity: error
      ruleType: VMwareRolePrivilege
      expressions:
        - '"InventoryService.Tagging.EditTag" IN (vmware_user_privileges)'
    - name: Network.Assign
      description: Validates that the root-level role has the Network.Assign privilege
      isEnabled: true
      severity: error
      ruleType: VMwareRolePrivilege
      expressions:
        - '"Network.Assign" IN (vmware_user_privileges)'
    - name: Sessions.ValidateSession
      description: >-
        Validates that the root-level role has the Sessions.ValidateSession
        privilege
      isEnabled: true
      severity: error
      ruleType: VMwareRolePrivilege
      expressions:
        - '"Sessions.ValidateSession" IN (vmware_user_privileges)'
    - name: StorageProfile.View
      description: Validates that the root-level role has the StorageProfile.View privilege
      isEnabled: true
      severity: error
      ruleType: VMwareRolePrivilege
      expressions:
        - '"StorageProfile.View" IN (vmware_user_privileges)'
    - name: StorageViews.View
      description: Validates that the root-level role has the StorageViews.View privilege
      isEnabled: true
      severity: error
      ruleType: VMwareRolePrivilege
      expressions:
        - '"StorageViews.View" IN (vmware_user_privileges)'