{{- if .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
data:
  username: {{ .Values.auth.username | b64enc }}
  password: {{ .Values.auth.password | b64enc }}
  vcenterServer: {{ .Values.auth.vcenterServer | b64enc }}
  insecureSkipVerify: {{ .Values.auth.insecureSkipVerify | b64enc }}
{{- end }}